### ISSUE TITLE
Title for paper

### ISSUE THREAD

**Issue by maximerischard** [maximerischard/temperature_model#12]
Any suggestions?

**Comment by karenamckinnon** [comment]
I always struggle thinking of titles, and usually put it off until the end. I suppose our choice also depends on the norms in the stat community -- do the titles tend to be cut and dry, or witty? 

A cut and dry option:

Ameliorating biases in daily maximum and minimum temperature measurements through Gaussian process modeling

but I'm sure there are better options in one of our brains.
