### ISSUE TITLE
Change stations used in SmallScaleHourly.ipynb

### ISSUE THREAD

**Issue by maximerischard** [maximerischard/temperature_model#3]
From Karen:

>  I'm quite surprised about the small l_x, and the fact that the four time series you show in the figure do indeed seem to have quite different behaviors. That said, the Caribou Island station is quite far from the other ones (~ 8 degrees, or ~800 km in longitude, and ~3 degrees in latitude). I suppose that larger difference in distance is built into the model, but it may be advantageous to use smaller distances between stations. In a paper we're writing using a spatial model for daily max and min, we use a compact covariance function with a lengthscale of ~600 km. 
> 
> Ah! And I see that you have chosen some challenging stations for other reasons. The first two stations (Cobourg and Port Weller) are right on Lake Ontario (google maps actually shows them on piers reaching out into the lake) whereas Peterborough is inland, at the airport. And, in addition to Caribou being farther west, it's actually in the middle of Lake Superior. These examples are actually highlighting some important factors we'll need to account for, namely the role of water bodies. Perhaps you could choose some stations in, e.g. the US midwest to make the problem a bit easier to begin with. My guess (hope?) is that the spatial correlation length scale will be much higher.

**Comment by maximerischard** [comment]
I want to use stations in Iowa, but I'm struggling to match the stations with their hourly data files. For example, which file corresponds to Des Moines?
USAF: 725460
WBAN: 14933
but there is no file 725460.14933.processed.2015.2015.csv

**Comment by karenamckinnon** [comment]
Just found a bug in my station saving code when checking this out! Hold tight, I'll fix this afternoon.

(As a more general answer, though, not all the stations in the station list file have valid (good) data, and I haven't saved csv files if all the data was flagged as being bad)

**Comment by maximerischard** [comment]
Aha, OK, I didn't realize that was going on. In that case, could you maybe suggest a set of 4-5 stations that are:
1. near each other
2. have good data
3. in a place with boring topology

**Comment by karenamckinnon** [comment]
Will do, but not until tomorrow.

**Comment by karenamckinnon** [comment]
OK! Here are four stations near to each other in IA in the updated data set

725450.14990.processed.2015.2015.csv
725460.14933.processed.2015.2015.csv
725480.94910.processed.2015.2015.csv
725485.14940.processed.2015.2015.csv

**Comment by maximerischard** [comment]
Thank you Karen! I've rerun the notebook with Iowan weather stations. The model actually behaves very well there. The fitted lengthscales are much more generous for both time and space.  Have a look:
https://github.com/maximerischard/temperature_model/blob/b0bc4e0/SmallScaleHourly.ipynb
