### ISSUE TITLE
Which day does a morning measurement get recorded as?

### ISSUE THREAD

**Issue by maximerischard** [maximerischard/temperature_model#9]
Let's say the Tn and Tx measurements get recorded every day at 17:00. It seems pretty clear that on October 14th, at 17:00, the daily high and low in the period spanning October 13th at 17:00 to October 14th at 17:00 gets read, and are recorded as the Tx and Tn for October 14th.

But in the scenario where the measurement gets made in the morning, say 8:00. Does the measurement made on October 14th at 8:00 get recorded as the Tx and Tn for October 14th, or for October 13th? It seems that the period being measured is mostly October 13th, but the measurement itself is made on the 14th, so I'm not sure what the convention is.

**Comment by karenamckinnon** [comment]
Good question. I can't answer with 100% certainty, but I'm fairly certain that the data would be associated with the day it is recorded. The original homogenization approach was outlined in Karl et al (1986), in which they discuss the fact that the data associated with a measurement taken at, e.g. 1am on the first day of a month (they were concerned with monthly averages) will contain 23 hours of the prior month and only one hour of the desired month. More recent docs (e.g. Menne et al, 2009) cite the Karl paper with reference to the homogenization approach, so my first guess would be that the temperatures are still associated with the day that they are recorded.
